### ISSUE TITLE
Unexpected behavior when restricting RT window (msconvert bug?)

### ISSUE THREAD

**Issue by magnuspalmblad** [524D/compareMS2#48] opened 2023-03-17 13:11 UTC
When restricting the RT windows to the range where peptides elute (e.g. 450 seconds to 3200 seconds), the distance between replicates is much larger than expected. It turns out that there is something wrong with thte RTINSECONDS field in the MGF files I used. They start near zero, and go up to 215,970 - or 60 hours (see last spectrum entry below). The actual runtime is 1 hour or 60 minutes.. When looking at the mzML file generated from the same Thermo RAW file, the retention time information is correct and given in minutes. So somewhere in msconvert, there is a multiplication with an extra factor 60 when going from minutes in these RAW files to seconds in the MGF.

This is probably a bug in msconvert, but it is definitely something to be aware of when using compareMS2, until the bug is fixed.

```
BEGIN IONS
TITLE=EXP002252022_82_NS45.54984.54984.3 File:"EXP002252022_82_NS45.raw", NativeID:"controllerType=0 controllerNumber=1 scan=54984"
RTINSECONDS=215970.2365
PEPMASS=360.88058230696498 170518.529266400001
CHARGE=3+
127.0014496 2900.3950195313
129.0182495 4259.2924804688
152.7816315 2907.8703613281
280.9050293 8623.7939453125
298.913269 3160.4228515625
342.8616333 3411.0026855469
347.2980347 2859.3852539063
360.8753052 3365.1352539063
361.024353 4421.7392578125
488.3608093 2881.3664550781
871.4108887 2943.2465820313
1106.881592 3156.4880371094
END IONS
```

**Comment by 524D** [comment] 2023-03-17 17:01
@magnuspalmblad
Hi Magnus,

I would like to report the bug to the ProteoWizard team so that they can fix MSConvert, however I cannot reproduce this. With the GSC11_24h_R1.raw that we also used in mzRecal the retention time looks okay (using MSConvert Version: 3.0.23073-144d34c, the latest).
Can you share your .raw file so I can check with the same data that you use?

**Comment by 524D** [comment] 2023-03-29 13:35
The problem doesn't occur with the latest MSConvert and your data, so it seems to be a problem with our MSConvert version. Since the MGF file doesn't contain information about the software/version with which it was produced, a "bug compatible" fix in compareMS2 isn't possible.
Also, adding a manual "MSConvert bug"switch to the UI would only be useful for a small number of people, and confuse the rest. Therefore, I'm closing without further action.

**Closed by 524D** 2023-03-29 13:35 UTC
Labels: bug
