### ISSUE TITLE
Error reading sample_to_species_mapping.txt

### ISSUE THREAD

**Issue by magnuspalmblad** [524D/compareMS2#37] opened 2022-03-28 10:22 UTC
When I try to run the primate example with the latest release (2.0.0-alpha.1), I get an unexpected behavior when using the accompanying sample_to_species_mapping.txt file. The output window goes blank (white) after half a second, and nothing else happens.

I can run the same release on the same files without the sample_to_species_mapping.txt file without problem.

I can replicate the behavior on my laptop and LUMC computer.

**Comment by 524D** [comment] 2022-03-30 14:57
This already fixed in the current GitHub version. As a workaround, you an also select a difference comparison order (e.g. random).
The cause is that with this dataset, the first comparison happens between two files of the Gorilla_gorilla species. When a sample-to-species file is used, the "comparems-to-distancematrices" executable outputs the distance between species, not between samples. In this case, there is only one specie, causing the output distance matrix to be empty. In the 2.0.0-alpha1  version, the phylotree javascript crashed when there is only once node and no distance. This is now fixed.

**Closed by 524D** 2022-03-30 14:57 UTC
Labels: bug
